##
## Copyright 2022 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  complex-logic:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false