#!/bin/sh

#This is *private* data that we can't have living on github. Keys, access tokens, ..

#For simplicity: use the following keys in both ethereum mainnet *and* in rinkeby. You need to have funds in both.

#To add funds to each:
# -mainnet: in Firefox -> metamask (logged in) -> send ETH to address below
# -rinkeby: use faucet https://testnet.help/en/ethfaucet/rinkeby
#
#Etherscan:
# mainnet: https://etherscan.io/
# rinkeby: https://rinkeby.etherscan.io/

# randomly generated via privatekeys.pw/ethereum/random
export OCEAN_PRIVATE_KEY1=cc9ecbe21eb30b7d9dd2808024b4f0da5876e7c7216b28ab6ecb0ccd1d4c76b7
#the key above has eth addr: 0x39Cd844DE27f20349CA2876E0E588c75107e0dA1
#mainnet info: https://etherscan.io/address/0x39cd844de27f20349ca2876e0e588c75107e0da1
#rinkeby info: https://rinkeby.etherscan.io/address/0x39cd844de27f20349ca2876e0e588c75107e0da1

export OCEAN_PRIVATE_KEY2=cc9ecbe21eb30b7d9dd2808024b4f0da5876e7c7216b28ab6ecb0ccd1d4c76b8
#the key above has eth addr: 0x759B04fEe93380a1CabdB94EDD15e026b79a281E

export OPF_PRIVATE_KEY=cc9ecbe21eb30b7d9dd2808024b4f0da5876e7c7216b28ab6ecb0ccd1d4c76b9
#the key above is typically a fake key. But for production deployment, we need the real one.
#the key above has eth addr: FIXME

export OCEAN_COMMUNITY_ADDRESS=0x102Baf0C52A358031F696A834c4C8b6df24F4092
#the address above is where L1 fees go to. It's typically a fake addres. For production deployment, we need the real one.


# (used also by web3.py)
export WEB3_INFURA_PROJECT_ID=357f2fe737db4304bd2f7285c5602d0d

