#
# Copyright 2021 Ocean Protocol Foundation
# SPDX-License-Identifier: Apache-2.0
#
ENV_CONFIG_FILE = "CONFIG_FILE"
ENV_PROVIDER_API_VERSION = "PROVIDER_API_VERSION"
ENV_INFURA_CONNECTION_TYPE = "INFURA_CONNECTION_TYPE"
ENV_INFURA_PROJECT_ID = "INFURA_PROJECT_ID"
