##
## Copyright 2022 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: black

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: psf/black@stable
        working-directory: ${{ github.workspace }}
        with:
          options: "--check --verbose"
          version: "22.10.0"
