##
## Copyright 2021 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: Ocean.py tests

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    environment:
      CC_TEST_REPORTER_ID: ${{ secrets. CC_TEST_REPORTER_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ocean.py
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install pypa/build
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
      - name: Publish package
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}

